### ISSUE TITLE
DB migrate Issue 

### ISSUE THREAD

**Issue by kimoali** [rossp/django-helpdesk#285]
Hello 

I'm trying to setup django helpdesk and I'm getting the below error when i run python manage.py migrate
I start new project and install all the requirements . and i did all the steps in the below link

http://django-helpdesk.readthedocs.org/en/latest/install.html

```Error 

=========================================================================== 
UnknownMigration: Migration 'helpdesk:0006_auto__add_field_ticket_tags' probably doesn't exist.
Traceback (most recent call last):
  File "/home/dhkuwaitw/virtual/lib/python2.6/site-packages/south/migration/base.py", line 313, in migration
    migration = __import__(full_name, {}, {}, ['Migration'])
  File "/home/dhkuwaitw/helpdesk/helpdesk/south_migrations/0006_auto__add_field_ticket_tags.py", line 6, in <module>
    from helpdesk.settings import HAS_TAG_SUPPORT
ImportError: cannot import name HAS_TAG_SUPPORT
=========================================================================== 
```
Regards .

**Comment by rossp** [comment]
I think the problem is that your parent module is called `helpdesk`. So when you `from helpdesk import settings` it'slooking at `/home/dhkuwaitw/helpdesk/settings` rather than `home/dhkuwaitw/helpdesk/helpdesk/settings`. 

Change the parent folder and try again - make sure you don't use a name in use by any other module you're working with.

**Comment by kimoali** [comment]
it is working now thanks
