### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by rando305** [rossp/django-helpdesk#290]
Is there a python3 version?  I have u"strings" that are failing.

**Comment by rossp** [comment]
No testing is currently done on python3, although there's no specific reason that's the case. We don't really do anything overly complicated, python-wise, so my guess is that this codebase can run easily enough on 2.6+ and 3.x

I'll admit, though, that I haven't ever used python 3 so I'd love any pull requests or comments from those that have been through the process before :)

**Comment by rossp** [comment]
From a cursory glance at the py3 docs right now, it appears we will need to do the following to get django-helpdesk compatible with both Python 2.x and 3.x. Thoughts?

- [ ] Update docs & installers to only support Python 2.6/2.7
- [ ] Confirm versions of Python 3 to support (Py 3.3 seems easiest at first glance)
- [ ] Get code running in Python 3.x
- [ ] Backport to also run on 2.6
- [ ] Update docs re Python 3
- [ ] Update release

**Comment by flinz** [comment]
@rossp i have added a PR for python 3 compatibility at https://github.com/rossp/django-helpdesk/pull/356.

I sincerely would abandon python 2.6 support, since even django 1.7 requires python >= 2.7 and we will discontinue support for django <= 1.6 soon (as [discussed earlier](https://github.com/rossp/django-helpdesk/pull/351#issuecomment-156769068))

This updates the todo to
 - [ ] Update docs & installers to only support Python 2.7/3.x
 - [ ] Confirm versions of Python 3 to support (Py 3.3 and 3.5 tested so far)
 - [x] Get code running in Python 3.x
 - [x] Backport to also run on 2.7
 - [ ] Update docs re Python 3
 - [ ] Update release
 - [ ] Update travis testing to include python 2.7, & 3.x

**Comment by rossp** [comment]
I've merged this in. Next stop: documentation & Travis.

**Comment by rossp** [comment]
Docs & Travis config updated. Release to be managed via #362. Thank you so much!
