### ISSUE TITLE
Proposition: Staff queue assignment / teams

### ISSUE THREAD

**Issue by flinz** [rossp/django-helpdesk#300]
Hi, I am currently adapting the Helpdesk for our usecase. I have to be able to assign some staff to take care/be able to see only tickets in certain queues.

Is this interesting as a feature in general for helpdesk?

If so, I would like some feedback on how to approach this best. As far as I see it there's three options:
* create a Team model, which contains a many-to-many mapping to Users, then many-to-many map the teams to queues. This would allow a simpler assignment of whole teams of users.
* extend queues with a many-to-many mapping to Users.
* do both, which allows a more flexible assignment of both teams of users or individuals to the queues.

**Comment by rossp** [comment]
I can see the benefit for this in larger orgs - but it'll quickly get pretty complex.

I'm tentatively supportive of this change if it doesn't complicate the initial setup or UI significantly. I've got a few things that need to be fleshed out before making any changes, though:

1. Does this need to function as an authorisation mechanism? Based on your submission, I think so.
    a. if I don't have access to the "Finance" queue, should I be able to see tickets in that queue? 
    b. If I can see them, can I edit them?
    c. If I can see them, can I add follow-ups?
    d. If I can see them, can I assign to someone who has access to that queue?
    e. Can I create a new ticket for that queue?
    f. If I can't see tickets in that queue, what happens after I create a ticket there?

2. Should there be superuser functionality? ie helpdesk manager gets to see all tickets

3. Does the email processor need to handle this?

3. How to best handle the "normal" use case, with no per-user queue management - eg keeping current functionality.

**Comment by reduxionist** [comment]
@flinz

I too need this functionality and am about to begin implementation, for our own use case at the very least, although hopefully it can be made to fit the broader requirements @rossp describes above. Do let me know if there's anything we should collaborate on yet, otherwise I will post an update once I have anything worth mentioning available to share.

**Comment by flinz** [comment]
@reduxionist cool man, I didn't start on it at all yet, so for now you're free to explore. I can be of assistance in testing, should you wish - right now im a bit short on time, so i wont really be up for a full collaboration, sorry.

**Comment by reduxionist** [comment]
@flinz I have completed a working version of this functionality.

I checked the merge against your GitHub HEAD [branch](/flinz/django-helpdesk/tree/real_local), and it failed due to a false conflict, so I have committed an already merged version to my own real_local [branch](/reduxionist/django-helpdesk/tree/real_local).

If you'd prefer to merge yourself, perhaps against some other branch, I recommend pulling from my squashed feature [branch](/reduxionist/django-helpdesk/tree/per-queue-staff-membership). Should you want to do any tinkering and think that the full commit history would give you insight into my dev process it is also [available](/reduxionist/django-helpdesk/tree/per-queue-staff-membership-full-history).

An import caveat is that for our needs it was sufficient merely to restrict queue display in list views, statistics and reports -- but not in ticket creation or editing, though it wouldn't be hard to add there either.

Please test it out and let me know how it goes so I can make any adjustments necessary before submitting an initial PR to origin.

Thanks!
Jonathan

**Comment by reduxionist** [comment]
Hi @rossp,

As just mentioned, I've completed an initial version of this functionality that works for our needs. It was quite straightforward to implement, a credit to the initial design of this app.

Here's how it addresses the initial specifications you brought up in this issue:

> Does this need to function as an authorisation mechanism?

Currently it does not, it only acts as a filter for list views (dashboard, ticket list/query, and reports). Our need was for staff members to have situational awareness for the queues they're responsible for and not be distracted by irrelevant information for queues they're not involved in. At the moment, it is not designed to prevent staff with malicious intent from interfering in queues they shouldn't. It should, however, prevent such interference from occurring accidentally.

>a. if I don't have access to the "Finance" queue, should I be able to see tickets in that queue? 

You can see tickets from queues you don't have access to only on an individual basis, and only if you know the ticket ID or URL. You will not see them in your dashboard, in search results (from either the "Tickets" link or the search bar), or in stats/reports views.

>b. If I can see them, can I edit them?

Yes.

> c. If I can see them, can I add follow-ups?

Yes.

>d. If I can see them, can I assign to someone who has access to that queue?

Yes.

>e. Can I create a new ticket for that queue?

Yes.

>f. If I can't see tickets in that queue, what happens after I create a ticket there?

Nothing different happens; you can see it directly because you know the ID and URL.

>Should there be superuser functionality? ie helpdesk manager gets to see all tickets

Yes, superuser is fully exempted from this restriction.

>Does the email processor need to handle this?

It does not.

> How to best handle the "normal" use case, with no per-user queue management - eg keeping current functionality.

The normal use case remains the default. Users will see no change unless they explicitly set HELPDESK_ENABLE_PER_QUEUE_STAFF_MEMBERSHIP setting to True.

If others want to restrict individual ticket actions by queue membership it should be easy to do so, but the appropriate responses for the scenarios discussed above are less obvious to me.

The patch includes a test-suite that is supposed to provide 100% coverage of new code; if you notice any gaps please do bring them to my attention and I will correct the omissions in short order. Additionally, minimal descriptions were added to the docs to explain the new feature.

As it has undergone only light internal use so far, I'll wait for @flinz's reply before submitting a PR, but please do let me know of any requests or suggestions you may have already and I'll do my best to incorporate them while it's all still fresh in my head.

Thanks!
Jonathan

**Comment by flinz** [comment]
Nice work!

There's one minor issue, which i have fixed in my [fork of your feature branch](https://github.com/flinz/django-helpdesk/tree/per-queue-staff-membership): the last migration in [master](https://github.com/rossp/django-helpdesk) seems to be 003_initial_data_import.py. You somehow had 004_initial_data_import.py, which broke the migrate continuity.

I also took the liberty and corrected and rephrased the [doc section in my merged branch](https://github.com/flinz/django-helpdesk/tree/per-queue-staff-membership/docs/settings.rst).

As to the non-authorization nature of the current state: It should be made clear that this is purely a view filtering and not a restriction of access - as it already is written in the documentation.

For a future release, I don't think limiting the ticket view/editing based on assigned queues would be hard to implement though, and it would be useful. I particularly have the use case where I have some staff members part of an external team, that should not be able to view internal queues.

**Comment by reduxionist** [comment]
Thanks @flinz!

I squashed and merged in your documentation and migration fix-ups into my feature branch; good catch on the migration I didn't update to account for my own merged PR!

I'll submit a PR from that and then we'll see what @rossp thinks before considering turning it into a full access control feature for viewing and editing individual tickets.

**Comment by rossp** [comment]
Wow, great work you two! Thanks for addressing my concerns directly, too - it wasn't a wishlist, but a list of things I thought we should consider and you did a great job of answering directly @reduxionist. I'm not 100% sure how well patching the user model admin will go with custom models/admins, bu tother than that I see no particular reason not to merge this as-is.

**Comment by rossp** [comment]
Fixed by #332 as far as I can tell. Happy to reopen or have new issues opened if/when we need to expand on this.
