### ISSUE TITLE
What UI do you use? 

### ISSUE THREAD

**Issue by maniachhz** [rossp/django-helpdesk#318]
Dear all,

The default UI of  django-helpdesk is bootstrap UI,  I feel it's not beautiful. I found that the helpdesk writen in PHP looks pretty.
What UI do you use? Can anyone send me a beautiful one? Thanks.

**Comment by maniachhz** [comment]
example:
http://www.hesk.com/demo.php

**Comment by rossp** [comment]
Saying that something is not beautiful simply because it uses Bootstrap isn't a helpful suggestion, sorry.

We switched to Bootstrap a while ago for two reasons:

1. Most people don't use out-of-box templates, they will customise django-helpdesk to match the rest of their site. To that end, many people *do* use Bootstrap so this seems like a sane starting point for them to do their customisation... and if they want to throw away bootstrap and use custom templates, that's also alright. 
2. If they don't want to customise the templates, Bootstrap is a "good enough" fit for  most people - it's relatively clean and simple and won't be too out of place on many websites. It also provides a familiar (to many) template structure to simplify out development process.

Further, my personal opinion is that the Hesk sample you've linked to looks like something out of the Windows XP era, and isn't a drop-in fit for most websites today in 2015. I would not want to update the default theming of django-helpdesk to match this.

**Comment by rolandf** [comment]
Hi,

I think that using Bootstrap is a wise choice. It can be easilly
customised with limited knowledge of CSS and you have a responsive website.

I clicked the Hesk demo link and closed it right away.
