### ISSUE TITLE
Issue updating ticket - " 'module' object has no attribute 'get_template_from_string' "

### ISSUE THREAD

**Issue by dominicfollett** [rossp/django-helpdesk#335]
I'm very new to django-helpdesk; I've looked at locales and included the template context processors in settings.py, but I keep getting the problem below when updating a ticket. I notice a similar stack trace when I run ./manage.py get_email. Can you please point me in the right direction?

![screenshot from 2015-07-08 15 38 02](https://cloud.githubusercontent.com/assets/9007502/8571515/a097a7a0-2587-11e5-93f7-5ab1611bc0ee.png)

**Comment by rossp** [comment]
Appears to be related to Django 1.8 removing `get_template_from_string` (#315) and needs to be properly addressed.

**Comment by dominicfollett** [comment]
I'll try a fix myself if I have time  - for now I'l downgrade to an earlier django version. Please let me know if there is a way I can help.

**Comment by flinz** [comment]
Yes, this is related to a function deprecated in Django 1.8. I have [a branch that fixes several issues with django 1.8](https://github.com/flinz/django-helpdesk/tree/django-1.8). Should you run into any problems, let me know.

**Comment by leidyj** [comment]
hi, i fixed this issue, i making the next, in views folder, in staff.py file added the next line in imports
from django.template import Engine

and changed, this line
comment = loader.get_template_from_string(comment).render(Context(context))

for this line
comment = Engine().from_string(comment).render(Context(request,context))

this worked for me, because if you is intalling django-helpdesk in a version newer(python >2.7 or django >1.8), get_template_from_string is incompatible.

pdt:  sorry for the english.

regards.

**Comment by reduxionist** [comment]
Thanks for adding your fix @leidyj 

@rossp There's now at least three versions of a fix for this (this latest one, @flinz's and my own); do you have any thoughts on how you'd like to handle providing for compatibility with multiple Django versions?

I have found [arteria/django-compat](https://github.com/arteria/django-compat) really helps with this kind of thing and has been worth adding the extra dependency for me.

Otherwise, as I understand the current [Django release policy](https://docs.djangoproject.com/en/1.8/internals/release-process/), since anything deprecated in version X is still supported through version X+1, IMO, it's simplest to support a range of 3 major releases (X - 1, X, X + 1). IIRC, currently django-helpdesk's minimum version is 1.5 and it works out-of-the-box through 1.7 -- so it fits this 3 major versions pattern. It is probably possible to provide 1.8 support without using any compatibility shims just by dropping 1.5 support (I say 'probably' because I'm not sure whether this release policy was already in place at the time of 1.5, but even if not, 3 versions seems like a good policy going forwards).

Anyway, if you let me know what your preferences are for handling this I'll try to package the version-compatibility fixes up into a PR that meets the corresponding criteria.

**Comment by rossp** [comment]
Thank you so much guys and sorry I haven't been able to follow this up.

I believe we should follow Django's policy of Current and Previous release. Given the decently long lead times for new major releases, we should be able to support eg Django 1.9 on release day, possibly stopping official support for 1.7 at that time. I do not believe our little project should support LTS releases given the project isn't even at 1.0 yet.

Any chance you can submit a pull request with your branch of 1.8 changes that covers more than just this template issue?

**Comment by reduxionist** [comment]
Great! I will submit a PR for 1.8 compatibility, dropping support for <=1.6, by this weekend.

**Comment by flinz** [comment]
@reduxionist next to templating issues, be sure to watch out for compatibility with the helpdesk tests. Django 1.8 removed some deprecated classes, so I had to adapt the quicktest.py (to fix those missing classes and ensure backwards compatibility) [https://github.com/flinz/django-helpdesk/commit/55dd80fa0621d9535bbd7672c57e9c5394a1159b & https://github.com/flinz/django-helpdesk/commit/05625d0bfd92cb3113d0e00808ef1cba596e9e71] and rename the test classes themselves to a common ``test_X.py`` scheme to make them auto-discoverable. 

I am unsure whether my renaming approach is the most straight forward, maybe you can have a second look.

**Comment by reduxionist** [comment]
Thanks for the tips @flinz! I will be sure to refer to (and probably cherry-pick and/or rebase from) the referenced commits. I had to work this past weekend so I probably won't get back to it until this weekend, however.

**Comment by flinz** [comment]
@reduxionist are you still on this (submitting a PR with 1.8, dropping <=1.6)?

Otherwise: what (besides changes in my branch) is there to do? Do you have a branch I can work off?

**Comment by reduxionist** [comment]
Alex, I haven't gotten around to this yet unfortunately, your own branch remains best starting point!

**Comment by flinz** [comment]
@rossp this can be closed.
