### ISSUE TITLE
the app does not account correctly tickets in stats

### ISSUE THREAD

**Issue by leidyj** [rossp/django-helpdesk#337]
hi, i created a ticket and i want the stats, but this does not account the tickets, thaks a lot for the help that can me to give.

![issue1](https://cloud.githubusercontent.com/assets/13768754/9334336/f4e9369e-4593-11e5-8793-cb526ac32a55.JPG)
![issue2](https://cloud.githubusercontent.com/assets/13768754/9334363/13b1fb7e-4594-11e5-875f-676de69404c3.JPG)

**Comment by rossp** [comment]
Can you please provide a bit more info - what version of Django, what database, and have you tried with a few extra tickets?

**Comment by leidyj** [comment]
The version is 3.4 for python and 1.8.3 for django and the database isdb.backends.mysql and with more tickets works the same way.

**Comment by reduxionist** [comment]
Are you using the per-queue staff membership access restriction feature? That is to say, have you set HELPDESK_ENABLE_PER_QUEUE_MEMBERSHIP = True? I'm guessing not, but best to be sure. 

What happens if you create a custom query in the ticket list?

Could you install the django-debug-toolbar and show us the SQL queries generated when viewing the page when it's not showing the desired result?

**Comment by leidyj** [comment]
hi, this is worked, thanks a lot, only i removed the encode utf8 , because i trying migrating a newer version.
