### ISSUE TITLE
Please Create a ChoiceStream Allias / Mailing List

### ISSUE THREAD

**Issue by oceansfine** [rossp/django-helpdesk#338]
Hi HelpDesk

Please set up this allias and please include the following on it:
choicestream@factual.com
Include: 
ocean
Glen
Janna

Thanks!

**Comment by rossp** [comment]
Where's GitHub's report spam function?

**Comment by reduxionist** [comment]
There's no per-message spam reporting, but they have been very responsive to spam I've reported via the [report user](https://github.com/contact?report=oceansfine) feature in the past.

Closes #338.

**Comment by rossp** [comment]
Thanks - in my head my comment was a bit more tongue in cheek but I appreciate that link; have reported the user because I *think* this is spam... but not very good spam if it is, doesn't even have a virus link or back story about rich beautiful eastern European brides with large inheritance to share!

**Comment by reduxionist** [comment]
Oh, hehe, oops! I was replying to a notification email so I blame the lack of context...
