### ISSUE TITLE
django sqllite database connect pycharm in linux

### ISSUE THREAD

**Issue by i25** [rossp/django-helpdesk#346]
SQLite -
           Native library cannot be loaded.
           org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
           java.lang.UnsatisfiedLinkError:

**Comment by rossp** [comment]
Please provide more information.
* What triggered this message, what were you trying to do?
* Please provide the rest of the stack trace
* Do other Django apps work, or is it only `django-helpdesk` that fails?
* If you remove `django-helpdesk` from `settings.INSTALLED_APPS` does everything work alright?

**Comment by i25** [comment]
![image](https://cloud.githubusercontent.com/assets/14994694/10929360/8be99116-82d8-11e5-9f0c-54d7325b0921.png)

**Comment by i25** [comment]
other Django apps works, it is  only django-helpdesk that fails.

**Comment by rossp** [comment]
I am wondering if this is another Python 3.x issue. Python 2.x and 3.x are quite different and there is not yet any formal Python 3.x support for `django-helpdesk` (if it works, it's an accident. Sorry.)

Two questions:

1. If you manually create a UserSettings record, does this work alright?  Given your issue in issue #347  I am guessing you'll continue having other Python 3 issues (see issue #290 for any future progress on this)
2. Can you please try with Python 2.7 instead of Python 3?

(Yes, I realise it's absurd there isn't any Python 3 support yet. Sorry again.)

**Comment by rossp** [comment]
Given lack of response here I am going to close it as it seems to be environmental - if it does turn out to be a Python 3 issue please re-test (see #290 for this addition).
