### ISSUE TITLE
Django 1.9 compatibility

### ISSUE THREAD

**Issue by flinz** [rossp/django-helpdesk#355]
In anticipation of the upcoming Django 1.9 release around December, i started a compatibility branch at https://github.com/flinz/django-helpdesk/tree/django-1.9-fixes. 

After some small fixes all tests pass under django 1.9b1, so no big changes involved. 
I will open a PR when the final 1.9 version is released.

**Comment by 9dogs** [comment]
Any news about 1.9 compatibility? It's been a week since release.

**Comment by flinz** [comment]
Ah, I forgot to follow up. Check [my branch](https://github.com/flinz/django-helpdesk/tree/django-1.9-fixes), if not much changed since the 1.9b1 it should still work. I will open a PR after i verified this.

**Comment by flinz** [comment]
@rossp we should update the travis checks for django 1.9 1.8 and 1.7 (dropping support for <= 1.6).

**Comment by alexbarcelo** [comment]
I was delighted to stumble upon this branch :)

However I have an issue, @flinz I hope you don't mind I comment it here because I couldn't open an issue on your branch. In line 1216 on `models.py`

    max_length='30',

why the quotes? Django complained about not being a "positive integer" which was solved by removing the quotes. Is this a behaviour of some Django 1.9 version? Or is this a Postgres behaviour? I haven't checked thoroughly (still haven't had time) but given that it was an easy fix and couldn't see a reason for the quotes...

**Comment by flinz** [comment]
@alexbarcelo Thanks for the spot, that indeed looks like a bug. I'll open a PR fixing it.

I didn't run into this on MYSQL flavored django at all, so it might as well be PGSQL.. 
The bug probably prevented you from even getting as far as ``./manage syncdb`` I guess?

**Comment by rossp** [comment]
Merged in 6187b0568c51fe3e67c2f9c77852c857eb949405 - release to be managed by #362 . Thank you so much guys.
